# Numpy

* Numerical Python
* Data Type : ndarray : similar to list : works with array : 50 times faster than lists : can perform numerical operations on array : we cannot perform mathmatical operations on lists.
* Collection of similar data type
* 1-D, 2-D, 3-D arrays possible
* ndarray : N - Dimentional Array

In [1]:
!pip install numpy

In [2]:
import numpy

In [3]:
arr = numpy.array([45,25,65,23,12])

In [4]:
type(arr)

numpy.ndarray

In [5]:
import numpy as np # numpy as np is used as alias everywhere so that its easier to use.

In [6]:
arr = np.array([12,54,23,85,22,101])

In [7]:
type(arr)

numpy.ndarray

In [10]:
#Checking version
np.__version__

'1.20.1'

In [11]:
# Creating array
#Way 1
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [12]:
#Way 2
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [13]:
list1 = [1,2,3,4]
tuple1 = (1,2,3,4)

In [14]:
np.array(list1) # List and tuple are same for np

array([1, 2, 3, 4])

In [15]:
np.array(tuple1) # List and tuple are same for np

array([1, 2, 3, 4])

In [17]:
arr1 = np.array([1,10,100,1000]) #Similar Data
arr1

array([   1,   10,  100, 1000])

In [18]:
arr2 = np.array(["a","b","c","d"]) #Similar Data
arr2

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [23]:
arr3 = np.array([1,2,3,"c"]) # Dis-similar data are all converted into string
arr3

array(['1', '2', '3', 'c'], dtype='<U21')

In [33]:
arr4 = np.array([1,2,3,4,5,3.2]) # all is converted into float
arr4

array([1. , 2. , 3. , 4. , 5. , 3.2])

In [34]:
arr4.shape # Checking the dimension of array

(6,)

In [38]:
arr4[5] # Elements can be accessed as in list

3.2

In [36]:
arr4[::-1]

array([3.2, 5. , 4. , 3. , 2. , 1. ])

In [37]:
arr4[::2]

array([1., 3., 5.])

# 2 - D Array

In [140]:
arr_2d = np.array([[4,5,6],[8,5,6],[11,4,7]]) # Matrix
print(arr_2d)

[[ 4  5  6]
 [ 8  5  6]
 [11  4  7]]


In [30]:
type(arr_2d)

numpy.ndarray

In [66]:
arr_2d.shape # Gives shape/dimension of the array

(3, 3)

In [42]:
arr_2d[2,2] # Accessing the elements of a 2-d array

7

In [41]:
arr_2d[0,0]

4

In [49]:
# Array with all ones and zeros
arr_1s = np.ones([4,7])
arr_1s

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [50]:
arr_1s = np.ones([4,])
arr_1s

array([1., 1., 1., 1.])

In [51]:
arr_1s = np.ones([7])
arr_1s

array([1., 1., 1., 1., 1., 1., 1.])

In [48]:
arr_0s = np.zeros([3,7])
arr_0s

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

# 3-D Array

In [53]:
arr_1s = np.ones([4,7,2]) # 4 Rows, 7 Coloumn each element have two values in form of array
arr_1s

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [58]:
arr_3d = np.array([[[4,2,5],[3,5,8]] , [[5,8,4],[6,4,9]]])
arr_3d

array([[[4, 2, 5],
        [3, 5, 8]],

       [[5, 8, 4],
        [6, 4, 9]]])

In [59]:
type(arr_3d)

numpy.ndarray

In [60]:
arr_3d.shape  # Gives shape/dimension of the array

(2, 2, 3)

In [65]:
arr_3d[1,1,2] # Last Element

9

# Array Reshaping

* changing shape(dimension) of array, we canadd remove dimensions and can edit number of elements in each dimention

In [67]:
arr = np.array([1,5,2,4,6,8,9,7])

In [68]:
arr.shape

(8,)

In [69]:
new_arr1 = arr.reshape(4,2)
new_arr1

array([[1, 5],
       [2, 4],
       [6, 8],
       [9, 7]])

In [70]:
new_arr2 = arr.reshape(2,4)
new_arr2

array([[1, 5, 2, 4],
       [6, 8, 9, 7]])

In [76]:
new_arr3 = arr.reshape(1,8)
new_arr3

array([[1, 5, 2, 4, 6, 8, 9, 7]])

In [75]:
new_arr4 = arr.reshape(8,1)
new_arr4

array([[1],
       [5],
       [2],
       [4],
       [6],
       [8],
       [9],
       [7]])

In [77]:
new_arr3.shape

(1, 8)

In [78]:
new_arr4.shape

(8, 1)

# Iterating in ARRAY

In [79]:
arr4

array([1. , 2. , 3. , 4. , 5. , 3.2])

In [81]:
for i in arr4:
    print(i)

1.0
2.0
3.0
4.0
5.0
3.2


In [83]:
arr5 = arr4.reshape(6,1) # Row MAtrix
arr5

array([[1. ],
       [2. ],
       [3. ],
       [4. ],
       [5. ],
       [3.2]])

In [84]:
for i in arr5: # Coloumn Matrix
    print(i)

[1.]
[2.]
[3.]
[4.]
[5.]
[3.2]


# Joining two arrays

In [101]:
arr1 = np.array([14,15,21,20,2,1])
arr2 = np.array([1,2,3])
arr3 = np.array(["a","b","c","d"])
arr4 = np.array(["1","2","3"])
arr5 = np.array([[1. ],
       [2. ],
       [3. ],
       [4. ],
       [5. ],
       [3.2]])
arr6 = np.array([1,2,3,4,5,3.2])
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)

[14 15 21 20  2  1]
[1 2 3]
['a' 'b' 'c' 'd']
['1' '2' '3']
[[1. ]
 [2. ]
 [3. ]
 [4. ]
 [5. ]
 [3.2]]
[1.  2.  3.  4.  5.  3.2]


In [86]:
arr5

array([[1. ],
       [2. ],
       [3. ],
       [4. ],
       [5. ],
       [3.2]])

In [105]:
arr5+arr5

array([[ 2. ],
       [ 4. ],
       [ 6. ],
       [ 8. ],
       [10. ],
       [ 6.4]])

In [106]:
arr5+arr6

array([[ 2. ,  3. ,  4. ,  5. ,  6. ,  4.2],
       [ 3. ,  4. ,  5. ,  6. ,  7. ,  5.2],
       [ 4. ,  5. ,  6. ,  7. ,  8. ,  6.2],
       [ 5. ,  6. ,  7. ,  8. ,  9. ,  7.2],
       [ 6. ,  7. ,  8. ,  9. , 10. ,  8.2],
       [ 4.2,  5.2,  6.2,  7.2,  8.2,  6.4]])

In [111]:
np.concatenate((arr3,arr4)) # Adding two string arrays

array(['a', 'b', 'c', 'd', '1', '2', '3'], dtype='<U1')

In [112]:
np.concatenate((arr1,arr2)) # Adding two interger arrays

array([14, 15, 21, 20,  2,  1,  1,  2,  3])

In [115]:
np.concatenate((arr2,arr3)) # Adding two dissimilar data converted into string

array(['1', '2', '3', 'a', 'b', 'c', 'd'], dtype='<U21')

In [116]:
np.concatenate((arr5,arr6)) # Dimensions should be same

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [119]:
arr6+arr5 # This plus sign is Mathmatical operation

array([[ 2. ,  3. ,  4. ,  5. ,  6. ,  4.2],
       [ 3. ,  4. ,  5. ,  6. ,  7. ,  5.2],
       [ 4. ,  5. ,  6. ,  7. ,  8. ,  6.2],
       [ 5. ,  6. ,  7. ,  8. ,  9. ,  7.2],
       [ 6. ,  7. ,  8. ,  9. , 10. ,  8.2],
       [ 4.2,  5.2,  6.2,  7.2,  8.2,  6.4]])

# Sorting

In [151]:
arr1 = np.array([14,15,21,20,2,1])
arr2 = np.array([1,2,3])
arr3 = np.array(["a","e","h","d"])
arr4 = np.array(["1","2","3"])
arr5 = np.array([[1. ],
       [2. ],
       [3. ],
       [4. ],
       [5. ],
       [3.2]])
arr6 = np.array([1,2,3,4,5,3.2])
arr7 = np.array(['a', 'e', 'h', 'd', '1', '2', '3'])
arr8 = np.array([[4,58,6,12,15],[5,8,12,10,1]])
arr9 = np.array([["f","5","7","Ye","He"],["E","W","0","s","1"]])
arr10 = np.array([[[4,2,5],[3,5,8]] , [[5,8,4],[6,4,9]]])
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)
print(arr7)
print(arr8)
print(arr9)
print(arr10)

[14 15 21 20  2  1]
[1 2 3]
['a' 'e' 'h' 'd']
['1' '2' '3']
[[1. ]
 [2. ]
 [3. ]
 [4. ]
 [5. ]
 [3.2]]
[1.  2.  3.  4.  5.  3.2]
['a' 'e' 'h' 'd' '1' '2' '3']
[[ 4 58  6 12 15]
 [ 5  8 12 10  1]]
[['f' '5' '7' 'Ye' 'He']
 ['E' 'W' '0' 's' '1']]
[[[4 2 5]
  [3 5 8]]

 [[5 8 4]
  [6 4 9]]]


In [121]:
np.sort(arr1) # Sorting

array([ 1,  2, 14, 15, 20, 21])

In [124]:
np.sort(arr3) # Sort according to alphabet

array(['a', 'd', 'e', 'h'], dtype='<U1')

In [126]:
np.sort(arr5) # Coloumn will be sorted as coloumn matrix

array([[1. ],
       [2. ],
       [3. ],
       [4. ],
       [5. ],
       [3.2]])

In [128]:
np.sort(arr5+arr6) #2-D and 3-D matrix are sorted row wise

array([[ 2. ,  3. ,  4. ,  4.2,  5. ,  6. ],
       [ 3. ,  4. ,  5. ,  5.2,  6. ,  7. ],
       [ 4. ,  5. ,  6. ,  6.2,  7. ,  8. ],
       [ 5. ,  6. ,  7. ,  7.2,  8. ,  9. ],
       [ 6. ,  7. ,  8. ,  8.2,  9. , 10. ],
       [ 4.2,  5.2,  6.2,  6.4,  7.2,  8.2]])

In [134]:
arr7 = np.concatenate((arr3,arr4))
arr7

array(['a', 'e', 'h', 'd', '1', '2', '3'], dtype='<U1')

In [135]:
np.sort(arr7)

array(['1', '2', '3', 'a', 'd', 'e', 'h'], dtype='<U1')

In [154]:
arr7.sort() # This method can also be used and it replaces the array with sorted array
arr7

array(['1', '2', '3', 'a', 'd', 'e', 'h'], dtype='<U1')

# Array Splitting 

In [1]:
arr = np.array([1,5,8,9,4,5,6,7])

In [4]:
np.split(arr,4)

[array([1, 5]), array([8, 9]), array([4, 5]), array([6, 7])]

In [10]:
new_arr = np.split(arr,4) # It splits array into 4 equal parts, and forms a list of arrays 
print(new_arr)

[array([1, 5]), array([8, 9]), array([4, 5]), array([6, 7])]


In [8]:
type(new_arr)

list

In [9]:
type(new_arr[1])

numpy.ndarray