# Numpy

* Numerical Python
* Data Type : ndarray : similar to list : works with array : 50 times faster than lists : can perform numerical operations on array : we cannot perform mathmatical operations on lists.
* Collection of similar data type
* 1-D, 2-D, 3-D arrays possible
* ndarray : N - Dimentional Array

In [1]:
!pip install numpy

In [2]:
import numpy

In [3]:
arr = numpy.array([45,25,65,23,12])

In [4]:
type(arr)

numpy.ndarray

In [5]:
import numpy as np # numpy as np is used as alias everywhere so that its easier to use.

In [6]:
arr = np.array([12,54,23,85,22,101])

In [7]:
type(arr)

numpy.ndarray

In [10]:
#Checking version
np.__version__

'1.20.1'

In [11]:
# Creating array
#Way 1
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [12]:
#Way 2
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [13]:
list1 = [1,2,3,4]
tuple1 = (1,2,3,4)

In [14]:
np.array(list1) # List and tuple are same for np

array([1, 2, 3, 4])

In [15]:
np.array(tuple1) # List and tuple are same for np

array([1, 2, 3, 4])

In [17]:
arr1 = np.array([1,10,100,1000]) #Similar Data
arr1

array([   1,   10,  100, 1000])

In [18]:
arr2 = np.array(["a","b","c","d"]) #Similar Data
arr2

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [23]:
arr3 = np.array([1,2,3,"c"]) # Dis-similar data are all converted into string
arr3

array(['1', '2', '3', 'c'], dtype='<U21')

In [33]:
arr4 = np.array([1,2,3,4,5,3.2]) # all is converted into float
arr4

array([1. , 2. , 3. , 4. , 5. , 3.2])

In [34]:
arr4.shape # Checking the dimension of array

(6,)

In [38]:
arr4[5] # Elements can be accessed as in list

3.2

In [36]:
arr4[::-1]

array([3.2, 5. , 4. , 3. , 2. , 1. ])

In [170]:
arr4[::2]

NameError: name 'arr4' is not defined

In [171]:
a=np.array([(1,2,3,4),(3,4,5,6),(7,8,9,10)]) # Accessing the elements
print(a,"\n")
print(a[1:,2],"\n")
print(a[1,0:],"\n")
print(a[1:,1:],"\n")

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 7  8  9 10]] 

[5 9] 

[3 4 5 6] 

[[ 4  5  6]
 [ 8  9 10]] 



In [178]:
arr = np.arange(5,20)#Creating array with continious sequensce using RESHAPE AND ARANGE
arr.reshape(3,5)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# 2 - D Array

In [136]:
arr_2d = np.array([[4,5,6],[8,5,6],[11,4,7]]) # Matrix
arr_2d = np.array([(4,5,6),(8,5,6),(11,4,7)]) # Round brackets can also be used
print(arr_2d)

[[ 4  5  6]
 [ 8  5  6]
 [11  4  7]]


In [30]:
type(arr_2d)

numpy.ndarray

In [66]:
arr_2d.shape # Gives shape/dimension of the array

(3, 3)

In [42]:
arr_2d[2,2] # Accessing the elements of a 2-d array

7

In [41]:
arr_2d[0,0]

4

In [49]:
# Array with all ones and zeros
arr_1s = np.ones([4,7])
arr_1s

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [50]:
arr_1s = np.ones([4,])
arr_1s

array([1., 1., 1., 1.])

In [51]:
arr_1s = np.ones([7])
arr_1s

array([1., 1., 1., 1., 1., 1., 1.])

In [48]:
arr_0s = np.zeros([3,7])
arr_0s

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

# 3-D Array

In [53]:
arr_1s = np.ones([4,7,2]) # 4 Rows, 7 Coloumn each element have two values in form of array
arr_1s

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [58]:
arr_3d = np.array([[[4,2,5],[3,5,8]] , [[5,8,4],[6,4,9]]])
arr_3d

array([[[4, 2, 5],
        [3, 5, 8]],

       [[5, 8, 4],
        [6, 4, 9]]])

In [59]:
type(arr_3d)

numpy.ndarray

In [60]:
arr_3d.shape  # Gives shape/dimension of the array

(2, 2, 3)

In [65]:
arr_3d[1,1,2] # Last Element

9

# Array Reshaping

* changing shape(dimension) of array, we canadd remove dimensions and can edit number of elements in each dimention

In [67]:
arr = np.array([1,5,2,4,6,8,9,7])

In [68]:
arr.shape

(8,)

In [69]:
new_arr1 = arr.reshape(4,2)
new_arr1

array([[1, 5],
       [2, 4],
       [6, 8],
       [9, 7]])

In [70]:
new_arr2 = arr.reshape(2,4)
new_arr2

array([[1, 5, 2, 4],
       [6, 8, 9, 7]])

In [76]:
new_arr3 = arr.reshape(1,8)
new_arr3

array([[1, 5, 2, 4, 6, 8, 9, 7]])

In [75]:
new_arr4 = arr.reshape(8,1)
new_arr4

array([[1],
       [5],
       [2],
       [4],
       [6],
       [8],
       [9],
       [7]])

In [77]:
new_arr3.shape

(1, 8)

In [185]:
new_arr4.shape

NameError: name 'new_arr4' is not defined

In [186]:
#Arranging two arrays vertically : Vertical Stack
from numpy import random 
import numpy as np
arr=np.random.randint(100,size=(2,10))
print(arr,"\n")
print(arr2)
arr2=np.random.randint(100,size=(2,10))
np.vstack((arr,arr2))


[[79 50 45 90 33 44 95 26 53 88]
 [18 69 18 62 57 91 61  1  2 19]] 

[[23 57 79 23 12 14 90 90 99 72]
 [30 47 62 33 46 60 83  8 88 99]]


array([[79, 50, 45, 90, 33, 44, 95, 26, 53, 88],
       [18, 69, 18, 62, 57, 91, 61,  1,  2, 19],
       [21, 40, 62, 52, 50, 92, 46, 82, 38, 25],
       [11, 42, 23, 68,  0, 25, 18, 26, 65, 66]])

In [188]:
##Arranging two arrays horizontly : Horizontal Stack
from numpy import random
arr1=np.random.randint(100,size=(2,2))
arr4=np.random.randint(100,size=(2,2))
np.hstack((arr1,arr4))

array([[11, 46, 86, 92],
       [22, 28, 26, 69]])

In [189]:
#Arranging two arrays vertically : Concatenation
from numpy import random 
import numpy as np
arr=np.random.randint(100,size=(2,10))
print(arr,"\n")
print(arr2)
arr2=np.random.randint(100,size=(2,10))
np.concatenate((arr,arr2))


[[ 6 49 37 73 75 36 37 33 89 31]
 [52 80 81  9 32 16 17  9 96 46]] 

[[21 40 62 52 50 92 46 82 38 25]
 [11 42 23 68  0 25 18 26 65 66]]


array([[ 6, 49, 37, 73, 75, 36, 37, 33, 89, 31],
       [52, 80, 81,  9, 32, 16, 17,  9, 96, 46],
       [76, 14, 58, 44, 75, 41, 41, 80, 43, 82],
       [14, 77, 26,  8, 65, 41, 22, 88, 47,  8]])

# Iterating in ARRAY

In [79]:
arr4

array([1. , 2. , 3. , 4. , 5. , 3.2])

In [81]:
for i in arr4:
    print(i)

1.0
2.0
3.0
4.0
5.0
3.2


In [83]:
arr5 = arr4.reshape(6,1) # Row MAtrix
arr5

array([[1. ],
       [2. ],
       [3. ],
       [4. ],
       [5. ],
       [3.2]])

In [84]:
for i in arr5: # Coloumn Matrix
    print(i)

[1.]
[2.]
[3.]
[4.]
[5.]
[3.2]


# Deleting any row or coloumn 

* np.delete(array_name,index,axis= 0 or 1)
* axis = 0 means row
* axis = 1 means coloumn

In [202]:
array = random.randint(20,size = (4,5))
array

array([[ 3,  7, 18,  5,  2],
       [ 7,  5,  3,  0,  4],
       [17,  7,  7, 13,  5],
       [18, 14,  3,  5, 13]])

In [204]:
np.delete(array, 2 , axis = 0) # axis = 0, thus deletes 2nd row

array([[ 3,  7, 18,  5,  2],
       [ 7,  5,  3,  0,  4],
       [18, 14,  3,  5, 13]])

In [205]:
np.delete(array, 2 , axis = 1) # axis = 1, thus deletes 2nd coloumn

array([[ 3,  7,  5,  2],
       [ 7,  5,  0,  4],
       [17,  7, 13,  5],
       [18, 14,  5, 13]])

# Joining two arrays

In [101]:
arr1 = np.array([14,15,21,20,2,1])
arr2 = np.array([1,2,3])
arr3 = np.array(["a","b","c","d"])
arr4 = np.array(["1","2","3"])
arr5 = np.array([[1. ],
       [2. ],
       [3. ],
       [4. ],
       [5. ],
       [3.2]])
arr6 = np.array([1,2,3,4,5,3.2])
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)

[14 15 21 20  2  1]
[1 2 3]
['a' 'b' 'c' 'd']
['1' '2' '3']
[[1. ]
 [2. ]
 [3. ]
 [4. ]
 [5. ]
 [3.2]]
[1.  2.  3.  4.  5.  3.2]


In [86]:
arr5

array([[1. ],
       [2. ],
       [3. ],
       [4. ],
       [5. ],
       [3.2]])

In [105]:
arr5+arr5

array([[ 2. ],
       [ 4. ],
       [ 6. ],
       [ 8. ],
       [10. ],
       [ 6.4]])

In [106]:
arr5+arr6

array([[ 2. ,  3. ,  4. ,  5. ,  6. ,  4.2],
       [ 3. ,  4. ,  5. ,  6. ,  7. ,  5.2],
       [ 4. ,  5. ,  6. ,  7. ,  8. ,  6.2],
       [ 5. ,  6. ,  7. ,  8. ,  9. ,  7.2],
       [ 6. ,  7. ,  8. ,  9. , 10. ,  8.2],
       [ 4.2,  5.2,  6.2,  7.2,  8.2,  6.4]])

In [111]:
np.concatenate((arr3,arr4)) # Adding two string arrays

array(['a', 'b', 'c', 'd', '1', '2', '3'], dtype='<U1')

In [112]:
np.concatenate((arr1,arr2)) # Adding two interger arrays

array([14, 15, 21, 20,  2,  1,  1,  2,  3])

In [115]:
np.concatenate((arr2,arr3)) # Adding two dissimilar data converted into string

array(['1', '2', '3', 'a', 'b', 'c', 'd'], dtype='<U21')

In [116]:
np.concatenate((arr5,arr6)) # Dimensions should be same

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [119]:
arr6+arr5 # This plus sign is Mathmatical operation

array([[ 2. ,  3. ,  4. ,  5. ,  6. ,  4.2],
       [ 3. ,  4. ,  5. ,  6. ,  7. ,  5.2],
       [ 4. ,  5. ,  6. ,  7. ,  8. ,  6.2],
       [ 5. ,  6. ,  7. ,  8. ,  9. ,  7.2],
       [ 6. ,  7. ,  8. ,  9. , 10. ,  8.2],
       [ 4.2,  5.2,  6.2,  7.2,  8.2,  6.4]])

# Sorting

In [151]:
arr1 = np.array([14,15,21,20,2,1])
arr2 = np.array([1,2,3])
arr3 = np.array(["a","e","h","d"])
arr4 = np.array(["1","2","3"])
arr5 = np.array([[1. ],
       [2. ],
       [3. ],
       [4. ],
       [5. ],
       [3.2]])
arr6 = np.array([1,2,3,4,5,3.2])
arr7 = np.array(['a', 'e', 'h', 'd', '1', '2', '3'])
arr8 = np.array([[4,58,6,12,15],[5,8,12,10,1]])
arr9 = np.array([["f","5","7","Ye","He"],["E","W","0","s","1"]])
arr10 = np.array([[[4,2,5],[3,5,8]] , [[5,8,4],[6,4,9]]])
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)
print(arr7)
print(arr8)
print(arr9)
print(arr10)

[14 15 21 20  2  1]
[1 2 3]
['a' 'e' 'h' 'd']
['1' '2' '3']
[[1. ]
 [2. ]
 [3. ]
 [4. ]
 [5. ]
 [3.2]]
[1.  2.  3.  4.  5.  3.2]
['a' 'e' 'h' 'd' '1' '2' '3']
[[ 4 58  6 12 15]
 [ 5  8 12 10  1]]
[['f' '5' '7' 'Ye' 'He']
 ['E' 'W' '0' 's' '1']]
[[[4 2 5]
  [3 5 8]]

 [[5 8 4]
  [6 4 9]]]


In [121]:
np.sort(arr1) # Sorting

array([ 1,  2, 14, 15, 20, 21])

In [124]:
np.sort(arr3) # Sort according to alphabet

array(['a', 'd', 'e', 'h'], dtype='<U1')

In [126]:
np.sort(arr5) # Coloumn will be sorted as coloumn matrix

array([[1. ],
       [2. ],
       [3. ],
       [4. ],
       [5. ],
       [3.2]])

In [128]:
np.sort(arr5+arr6) #2-D and 3-D matrix are sorted row wise

array([[ 2. ,  3. ,  4. ,  4.2,  5. ,  6. ],
       [ 3. ,  4. ,  5. ,  5.2,  6. ,  7. ],
       [ 4. ,  5. ,  6. ,  6.2,  7. ,  8. ],
       [ 5. ,  6. ,  7. ,  7.2,  8. ,  9. ],
       [ 6. ,  7. ,  8. ,  8.2,  9. , 10. ],
       [ 4.2,  5.2,  6.2,  6.4,  7.2,  8.2]])

In [134]:
arr7 = np.concatenate((arr3,arr4))
arr7

array(['a', 'e', 'h', 'd', '1', '2', '3'], dtype='<U1')

In [4]:
np.sort(arr7) # First numbers then alphabet

NameError: name 'arr7' is not defined

In [154]:
arr7.sort() # This method can also be used and it replaces the array with sorted array
arr7

array(['1', '2', '3', 'a', 'd', 'e', 'h'], dtype='<U1')

# Array Splitting 

In [1]:
arr = np.array([1,5,8,9,4,5,6,7])

In [4]:
np.split(arr,4)

[array([1, 5]), array([8, 9]), array([4, 5]), array([6, 7])]

In [10]:
new_arr = np.split(arr,4) # It splits array into 4 equal parts, and forms a list of arrays 
print(new_arr)

[array([1, 5]), array([8, 9]), array([4, 5]), array([6, 7])]


In [8]:
type(new_arr) # It Splits array into list of array

list

In [9]:
type(new_arr[1])# Each elements are array

numpy.ndarray

In [2]:
np.split(arr,2)

[array([1, 5, 8, 9]), array([4, 5, 6, 7])]

In [3]:
np.split(arr,3) # Cannot split as it is not divisible into 3 equal parts

ValueError: array split does not result in an equal division

# Array Searching

In [14]:
arr1 = np.array(['a', 'e', 'h', 'd', '1', '2', '3'])

In [9]:
np.where(arr1 == "a") # Returns the index of the searched element

(array([0]),)

In [11]:
np.where(arr1 == "h") # Returns the index

(array([2]),)

In [15]:
np.where(arr1 == "1")

(array([4]),)

In [16]:
arr2 = np.array([1,5,8,9,4,5,6,7])

In [19]:
np.where(arr2 == 5) # Will retuen all the indexs, if item is present multiple times in form of tuple

(array([1, 5]),)

In [21]:
a = np.where(arr2 == 5)

In [22]:
type(a)

tuple

In [23]:
print(a)

(array([1, 5]),)


In [24]:
type(a[0])

numpy.ndarray

In [26]:
np.where(arr2 == 10) # Return blank if nothing found

(array([], dtype=int64),)

# Filter

* It is method of getting some elements out of a existing array ad create a new array.
* Boolean index list is used for filtering an array in numpy
* Used to subset the data
* Conditions can also be used to filter

In [27]:
arr1

array(['a', 'e', 'h', 'd', '1', '2', '3'], dtype='<U1')

In [30]:
filter = [True, False, False, True, False, False, True]

In [32]:
arr1[filter] # Filters according to the booleans

array(['a', 'd', '3'], dtype='<U1')

In [33]:
arr1

array(['a', 'e', 'h', 'd', '1', '2', '3'], dtype='<U1')

In [36]:
arr1[arr1 == "h"] # Using conditions to filter. Conditions can be implimented using for, if etc also

array(['h'], dtype='<U1')

# Random Numbers in Numpy
* random.rand() , gives random float b/w 0 and 1
* It has to be imported separately in numpy ( random.randint )
* If not imported separately, we use (numpy.random.randint)
* random.choice(), this helps user to generate random numbers from given set of numbers

In [43]:
x = np.random.randint(100) # Without importing
print(x)

3


In [45]:
from numpy import random
x = random.randint(100) # With  Importing
print(x)

99


In [49]:
random_arr = random.randint(50,100, size=(100)) # It creats an array of 100 random numbers from 50 to 100
print(random_arr)

[57 83 77 91 99 93 58 95 89 73 54 55 63 50 51 58 85 61 90 86 98 54 97 69
 89 71 96 62 64 70 50 58 86 52 98 74 79 80 61 80 64 94 78 80 92 87 97 80
 58 80 64 55 69 92 92 91 79 80 65 97 51 89 58 57 67 79 83 56 64 93 72 80
 65 96 91 69 70 51 77 80 97 65 84 85 53 90 68 50 92 68 62 60 64 63 99 93
 99 63 87 77]


In [50]:
type(random_arr)

numpy.ndarray

In [56]:
random_2darray = random.randint(10,100,size=(4,7)) #Creats a random 4 X 7 array(matrix), with numbers from 10 to 100
print(random_2darray)

[[52 18 21 45 79 14 99]
 [60 73 44 61 14 43 77]
 [86 93 49 79 96 88 78]
 [37 19 12 59 41 24 84]]


In [58]:
random_1darr = random.choice([2,4,8,6,2,5,5,7,5,1,0,2,1], size=(5)) # Random generated from given list of numbers
random_1darr

array([2, 0, 5, 2, 1])

In [59]:
random_2darr = random.choice([2,4,8,6,2,5,5,7,5,1,0,2,1], size=(5,3))  # Random generated from given list of numbers
random_2darr

array([[1, 5, 1],
       [2, 5, 5],
       [2, 2, 5],
       [2, 2, 5],
       [2, 7, 4]])

In [73]:
x = random.rand() # This gives float values bw 0 to 1.  Single number
x

0.35177301785493786

In [74]:
x = random.rand(5) # 1D Array
x

array([0.71383567, 0.40269269, 0.1801978 , 0.87489518, 0.56273437])

In [71]:
x = random.rand(3,5) # 2D Array
x

array([[0.29005571, 0.03838875, 0.26724333, 0.55469377, 0.09942821],
       [0.49378034, 0.79373064, 0.10741003, 0.89072257, 0.68688832],
       [0.15707969, 0.7697064 , 0.40777031, 0.45431943, 0.82340596]])

# Numpy Matrix Operations

In [95]:
arr1d_1 = random.randint(50,size=5)
print(arr1d_1)
arr1d_2 = random.randint(10,size=5)
print(arr1d_2)

[45  2  3 30  3]
[5 0 9 1 4]


In [96]:
arr1d_1+arr1d_2 #Math Addition on matrix

array([50,  2, 12, 31,  7])

In [103]:
arr2d_1 = random.randint(50,size=(2,3))
print(arr2d_1)
arr2d_2 = random.randint(10,size=(2,3))
print(arr2d_2)

[[42 18  1]
 [27 38 29]]
[[5 8 7]
 [7 8 3]]


In [108]:
arr2d_1+arr2d_2  # 2D array addition

array([[47, 26,  8],
       [34, 46, 32]])

In [110]:
arr2d_2-arr2d_1 # 2D Substraction

array([[-37, -10,   6],
       [-20, -30, -26]])

In [106]:
np.dot(arr1d_1,arr1d_2) # Dot Product of two 1D

294

In [112]:
arr1d_1

array([45,  2,  3, 30,  3])

In [113]:
np.dot(arr1d_1,5) # Scalar X Vector, 5X all elements

array([225,  10,  15, 150,  15])

In [120]:
np.dot(arr2d_1,arr2d_2) # for 2D Array this function performs matrix multiplication. m*n X n*p = m*p kind of like cross multiplication

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [117]:
arr2d_3 = random.randint(50,size=(2,3))
print(arr2d_3)
arr2d_4 = random.randint(10,size=(3,4))
print(arr2d_4)

[[28 35  2]
 [ 6 29  4]]
[[1 2 7 7]
 [1 7 1 0]
 [9 5 0 6]]


In [119]:
np.dot(arr2d_3,arr2d_4)

array([[ 81, 311, 231, 208],
       [ 71, 235,  71,  66]])

# Assignment / Revision

In [121]:
import numpy as np

In [122]:
# Checking Version
np.__version__

'1.20.1'

In [123]:
arr = np.array([5,8,7,9,6])

In [134]:
arr = np.array([[5,4,7],[6,8,9],[8,5,1],[0,4,5]])
arr1 = np.array([(5,4,7),(6,8,9),(8,5,1),(0,4,5)])
print(arr1)
print(arr)

[[5 4 7]
 [6 8 9]
 [8 5 1]
 [0 4 5]]
[[5 4 7]
 [6 8 9]
 [8 5 1]
 [0 4 5]]


In [125]:
arr

array([[5, 4, 7],
       [6, 8, 9],
       [8, 5, 1],
       [0, 4, 5]])

In [126]:
np.shape(arr)

(4, 3)

In [131]:
from numpy import random
arr = random.randint(10, size = (2,4))
arr

array([[7, 6, 8, 2],
       [7, 3, 2, 4]])

In [137]:
array=np.array([1,2,3,4,5,6])
print(array[-5:-1])

[2 3 4 5]


In [145]:
a=np.array([(1,2,3,4),(3,4,5,6),(7,8,9,10)]) # Accessing the elements
print(a,"\n")
print(a[1:,2],"\n")
print(a[1,0:],"\n")
print(a[1:,1:],"\n")

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 7  8  9 10]] 

[5 9] 

[3 4 5 6] 

[[ 4  5  6]
 [ 8  9 10]] 



In [154]:
print(a[:,0]) # First coloumn
print(a[1]) # Second Row
print(a[2]) # Third Row

[1 3 7]
[3 4 5 6]
[ 7  8  9 10]


In [155]:
a = np.array([(1,5,9),(10,12,2),(5,7,8)]) #  Row and Coloumn Operations
print(a)
print(a[0].max())
print(a[0].min())
print(a[1].sum())

[[ 1  5  9]
 [10 12  2]
 [ 5  7  8]]
9
1
24


In [161]:
list1 = [1,2,3,4,5,6]
arr = np.array(list1)
print(arr)
print(arr[::2])

[1 2 3 4 5 6]
[1 3 5]


In [169]:
a = random.randint(20, size = (4,3)) # Array reshaping
print(a)
print(np.reshape(a,(6,2)))
print(a.reshape(3,4))


[[10 12  4]
 [ 4  2  8]
 [12  0 15]
 [ 8  8  1]]
[[10 12]
 [ 4  4]
 [ 2  8]
 [12  0]
 [15  8]
 [ 8  1]]
[[10 12  4  4]
 [ 2  8 12  0]
 [15  8  8  1]]


In [182]:
#Arranging two arrays vertically : Vertical Stack
from numpy import random 
import numpy as np
arr=np.random.randint(100,size=(2,10))
print(arr,"\n")
print(arr2)
arr2=np.random.randint(100,size=(2,10))
np.vstack((arr,arr2))


[[74 97 22 84 14  6 79 25 41 78]
 [94 75  6  6 39  4 10 48  5 79]] 

[[87 52 79 15 76 34 34  4 20  2]
 [86  8 96  2 80 47 75 67 63 94]]


array([[74, 97, 22, 84, 14,  6, 79, 25, 41, 78],
       [94, 75,  6,  6, 39,  4, 10, 48,  5, 79],
       [23, 57, 79, 23, 12, 14, 90, 90, 99, 72],
       [30, 47, 62, 33, 46, 60, 83,  8, 88, 99]])

In [183]:
from numpy import random
arr1=np.random.randint(100,size=(2,2))
arr4=np.random.randint(100,size=(2,2))
np.vstack((arr1,arr4))

array([[97, 33],
       [ 2, 29],
       [73, 64],
       [18, 97]])

In [187]:
##Arranging two arrays horizontly : Horizontal Stack
from numpy import random
arr1=np.random.randint(100,size=(2,2))
arr4=np.random.randint(100,size=(2,2))
np.hstack((arr1,arr4))

array([[99, 89, 45, 53],
       [60, 54, 46, 87]])

In [191]:
arr = np.array([1,2,4,5])
np.where(arr == 5)

(array([3]),)

In [192]:
# Deleting and replacing a coloumn
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [197]:
sampleArray[:,1] = [0,0,0]
# OR this can also be written : sampleArray[:,1] = np.array([0,0,0])

In [196]:
sampleArray

array([[34,  0, 73],
       [82,  0, 12],
       [53,  0, 66]])

In [198]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [200]:
sampleArray[2,:] = [0,0,0]
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [ 0,  0,  0]])